name: InstantRestock
version: 2.2
author: spartacus04
main: me.spartacus04.instantrestock.InstantRestock
api-version: 1.19
description: plugin to allow villagers to have infinite trades

commands:
  instantrestock:
    description: Reloads the plugin
    usage: /instantrestock
    permission: instantrestock.reload
permissions:
  instantrestock.reload:
    description: Allows the player to reload the plugin
    default: op