name: InstantRestock
version: 2.3.1
author: spartacus04
main: me.spartacus04.instantrestock.InstantRestock
api-version: 1.14
description: plugin to allow villagers to have infinite trades

commands:
  instantrestock:
    description: Main command of the plugin
    usage: /instantrestock
    aliases:
      - infinitetrading

permissions:
  instantrestock.*:
    children:
      - instantrestock.reload
      - instantrestock.config
  instantrestock.reload:
    description: Allows the player to reload the plugin
    default: op
  instantrestock.config:
    description: Allows the player to edit the config
    default: op